app/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views as app_views
from django.contrib.auth import views as auth_views



urlpatterns = [

    path('', app_views.index, name='index'),
    path('<int:album_id>/', app_views.detail, name='detail'),
    path('songs/<str:filter_by>/', app_views.song, name='songs'),
    path('register/', app_views.register, name='register'),
    path('login/', app_views.login_user, name='login'),
    path('logout/', app_views.logout_user, name='logout'),
    path('create_album/', app_views.album_creation, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', app_views.create_song, name='create_song'),
    path('delete_album/<int:album_id>/', app_views.delete_album, name='delete_album'),
    path('delete_song/<int:album_id>/<int:song_id>/', app_views.delete_song, name='delete_song'),
    path('favorite_album/<int:album_id>/', app_views.favourite, name='favorite_album'),
    path('favorite/<int:song_id>/', app_views.favourite_song, name='favorite'),
]

music/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from app import views as app_views


r1 = routers.SimpleRouter()
r1.register(r'songs', app_views.Song, basename='Song')
#r1.register(r'song/{pk}/', app_views.SongDetail, basename='Song')
r1.register(r'albums', app_views.Album, basename='Album')
#r1.register(r'albums/{pk}/', app_views.AlbumDetail, basename='Album')
r1.register(r'users', app_views.User, basename='User')
#r1.register(r'users/{pk}/', app_views.UserDetail, basename='User')

urlpatterns = [
    path('api/', include(r1.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('music/', include(('app.urls', 'app'), namespace='music')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .forms import AlbumForm, SongForm, UserForm, User, Album, Song
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .serializers import *
from rest_framework import mixins, generics, viewsets
from rest_framework import permissions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse


class IsOwnerOrReadOnly(permissions.BasePermission):

    def has_permission(self, request, view):
        if request.method in permissions.SAFE_METHODS:
            return True

        # Write permissions are only allowed to the owner of the snippet.
        return bool(request.user.is_authenticated)

    def has_object_permission(self, request, view, obj):
        # Read permissions are allowed to any request,
        # so we'll always allow GET, HEAD or OPTIONS requests.

        if request.method in permissions.SAFE_METHODS:
            return True

        # Write permissions are only allowed to the owner of the snippet.
        return obj.user == request.user


class IsSongOwnerOrReadOnly(permissions.BasePermission):

    def has_permission(self, request, view):
        if request.method in permissions.SAFE_METHODS:
            return True

        # Write permissions are only allowed to the owner of the snippet.
        return bool(request.user.is_authenticated)

    def has_object_permission(self, request, view, obj):
        # Read permissions are allowed to any request,
        # so we'll always allow GET, HEAD or OPTIONS requests.
        if request.method in permissions.SAFE_METHODS:
            return True

        # Write permissions are only allowed to the owner of the snippet.
        return obj.album.user == request.user


AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


#api views


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'users': reverse('user-list', request=request, format=format),
        'albums': reverse('album-list', request=request, format=format),
        'songs': reverse('song-list', request=request, format=format)
    })


class Song(viewsets.ModelViewSet):

    serializer_class = SongSerializer
    queryset = Song.objects.all()
    permission_classes = [IsSongOwnerOrReadOnly, ]


class Album(viewsets.ModelViewSet):

    queryset = Album.objects.all()
    serializer_class = AlbumSerializer
    permission_classes = [IsOwnerOrReadOnly,]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class User(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [IsOwnerOrReadOnly, ]





#normal views

@login_required(login_url='/music/login/')
def index(request):
    albums = Album.objects.filter(user=request.user)
    query = request.GET.get('q','')
    if query:
        albums = albums.filter(Q(title__contains=query)| Q(artist__contains=query)).distinct()
        songs = Song.objects.filter(Q(song_name__contains=query)).distinct()
        context = {
            'songs': songs,
            'albums': albums
        }
        return render(request, 'app/index.html', context)

    else:
        return render(request, 'app/index.html', {'albums': albums})


@login_required(login_url='/music/login/')
def album_creation(request):
    form = AlbumForm(request.POST or None,
                     request.FILES or None)
    print('b')

    if form.is_valid():
        album = form.save(commit=False)
        album.user = request.user
        title = form.cleaned_data.get('title')
        album.logo = request.FILES['logo']
        logo = album.logo.url.split('.')[-1].lower()
        print('a')
        if logo not in IMAGE_FILE_TYPES:
            context = {
                'error_message': 'file type not supported',
                'form': AlbumForm(instance=album)
            }
            return render(request, 'app/create_album.html', context)

        album.save()
        messages.success(request, f'{title} is created')
        print('c')
        return render(request, 'app/detail.html', {'album': album})

    print('d')

    return render(request, 'app/create_album.html', {'form':AlbumForm()})


@login_required(login_url='/music/login')
def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album,
        'user': request.user
    }
    return render(request, 'app/detail.html', context)


@login_required(login_url='/music/login/')
def delete_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('app:index')


@login_required(login_url='/music/login/')
def create_song(request, album_id):
    print('a')
    album = get_object_or_404(Album, pk=album_id)
    form = SongForm(request.POST or None,
                    request.FILES or None)

    if form.is_valid():
        print('b')
        song = form.save(commit=False)
        song.album = album
        name = song.song_name
        song.audio = request.FILES["audio"]
        extension = song.audio.url.split('.')[-1]  #Important form.cleaned_data.get('audio').url.split(.')[-1]
        if extension not in AUDIO_FILE_TYPES:       ## is wrong !!!
            context = {
                'error_message': 'file type not supported',
                'form': form,
                'album': album
            }
            return render(request, 'app/create_song.html',  context)

        song.save()
        messages.success(request, f'{name} is created in{album.title} album')
        return redirect('app:index')


    else:
        print('c')
        return render(request, 'app/create_song.html', {'form': form,
                                                        'album': album})


@login_required(login_url='/music/login/')
def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = get_object_or_404(Song, pk=song_id)
    name = song.song_name
    song.delete()
    album.save()
    messages.success(request, f'{name} is deleted!!')
    return redirect('app:index')


@login_required(login_url='/music/login/')
def favourite_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    if song.is_favourite:
        song.is_favourite=False
    else:
        song.is_favourite=True
    song.save()
    return redirect('app:index')


@login_required(login_url='/music/login/')
def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    if album.is_favourite:
        album.is_favourite = False
    else:
        album.is_favourite = True
    album.save()
    return redirect('app:index')


def register(request):

    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        user = User.objects.create_user(username, email, password)
        user.set_password(password)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            user.save()
            login(request, user)
            albums = Album.objects.filter(user=request.user)
            context = {'albums': albums}
            print('NOtns,djbjssdc ')
            return render(request, 'app/index.html', context)
        else:
            return render(request, 'app/login.html', {'error_message': 'account disabled'})

    else:
        form = UserForm()
        context = {'form': form}
        return render(request, 'app/register.html', context)


def login_user(request):
    print(request.user)
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print('logged in')
            albums = Album.objects.filter(user=request.user)
            context = {'albums': albums}
            print('NOtns,djbjssdc ')
            return render(request, 'app/index.html', context)
        else:
            return render(request, 'app/login.html', {'error_message': 'Invalid lOGIN'})

    return render(request, 'app/login.html')


@login_required(login_url='/music/login/')
def logout_user(request):
    logout(request)
    return render(request, 'app/login.html')


@login_required(login_url='/music/login/')
def song(request, filter_by):
    albums = Album.objects.filter(user=request.user)
    songs = []

    songs = Song.objects.filter(album__in=albums)

    if filter_by == 'favorites':
        songs = songs.filter(is_favourite=True)
    return render(request, 'app/songs.html', {'songs': songs,
                                              'filter_by': filter_by})

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}App Music{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'app/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'app:index' %}">App Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'app:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'app:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:index' %}">
                <div class="form-group">
                    <input type="text" placeholder="Search" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'app:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

app/templates/app/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}App Music{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'app/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'app:index' %}">App Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'app:login' %}">Log In</a></li>
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'app:register' %}">Register</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

app/templates/app/create_album.html
{% extends 'app/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
                <div class="card panel-form">
                    <h3 class="page-title">Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'app/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>

</div>
{% endblock %}

app/templates/app/create_song.html
{% extends 'app/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'app:detail' album.id %}">
                            {% if album.logo %}
                                <img src="{{ album.logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'app:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'app:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 class="page-title">Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'app/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

app/templates/app/detail.html
{% extends 'app/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'app:detail' album.id %}">
                        {% if album.logo %}
                            <img src="{{ album.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.artist }}</h1>
                    <p class="album-title">{{ album.title }}</p>
                    <h6 class="genre">{{ album.genre }}</h6>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'app:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'app:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_name }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'app:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'app:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

app/templates/app/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3 id="user-name">{{ user.username }}'s Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'app:detail' album.id %}">
                            <img src="{{ album.logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h4>{{ album.artist }}</h4>
                            <p>{{ album.title }}</p>

                            <!-- View Details -->
                            <a href="{% url 'app:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'app:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'app:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'app:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_name }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'app:detail' song.album.id %}">
                                                <img src="{{ song.album.logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'app:detail' song.album.id %}">{{ song.album.title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'app:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

app/templates/app/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>m dmslk</title>
</head>
<body>
    <h1>hii sEXyyy</h1>
    <a href="{% url 'app:logout' %}"> logout</a>
</body>
</html>

app/templates/app/login.html
{% extends 'app/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="card card-container">
                    <h1 class="page-title">Login</h1>
                    <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
                    <p id="profile-name" class="profile-name-card"></p>
                    <form class="form-signin" role="form" action="{% url 'app:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input class="form-control" id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input class="form-control" id="id_password" maxlength="30" name="password" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
                            </div>
                        </div>
                    </form>
                    <div class="panel-signup">
                      Don't have an account? <a class="forgot-password" href="{% url 'app:register' %}">Click here</a> to register.
                    </div>
                    {% if error_message %}
                        <p class="error_message"><strong>{{ error_message }}</strong></p>
                    {% endif %}
            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/app/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h2> You are successfully logged out</h2>
<a href="{% url 'app:login' %}">Click here to log in</a>

</body>
</html>